# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug32
endif
export config

PROJECTS := gll

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

gll: 
	@echo "==== Building gll ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f gll.make

clean:
	@${MAKE} --no-print-directory -C . -f gll.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug32"
	@echo "   release32"
	@echo "   debug64"
	@echo "   release64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   gll"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
